all: px_test

CFLAGS = -g -Wall -O -I../../portaudio/pa_common -I../px_common

px_test: px_test.o px_mac_core.o ../px_common/portmixer.h
	gcc -g -o px_test px_test.o px_mac_core.o -lm \
		../../portaudio/pa_mac_core/portaudio.a -lpthread \
		-framework CoreAudio -framework AudioToolbox

px_test.o: px_test.c ../px_common/portmixer.h
	gcc $(CFLAGS) -c px_test.c


px_mac_core.o: ../px_mac_core/px_mac_core.c ../px_common/portmixer.h
	gcc $(CFLAGS) -c ../px_mac_core/px_mac_core.c


