# Add -g for adding debug information.
# Download MinGW GDB and add it to MinGW/bin file
main:
	gcc -c -o study.o src/study.c
	gcc -o study study.o
	gcc -c -o study2.o src/study2.c
	gcc -o study2 study2.o
	gcc -c -o study3.o src/study3.c
	gcc -o study3 study3.o
	gcc -c -o study4.o src/study4.c
	gcc -o study4 study4.o
	gcc -c -o study5.o src/study5.c
	gcc -o study5 study5.o
	gcc -c -o study6.o src/study6.c
	gcc -o study6 study6.o
	gcc -c -o study7.o src/study7.c
	gcc -o study7 study7.o
	gcc -c -o study72.o src/study72.c
	gcc -o study72 study72.o
	gcc -c -o study73.o src/study73.c
	gcc -o study73 study73.o
	gcc -c -o study8.o src/study8.c
	gcc -o study8 study8.o
	gcc -c -o iodes.o src/iodes.c
	gcc -o iodes iodes.o
	gcc -c -o test.o src/test.c -O
	gcc -o test test.o
clean:
	del study.o study.exe
	del study2.o study2.exe
	del study3.o study3.exe
	del study4.o study4.exe
	del study5.o study5.exe
	del study6.o study6.exe
	del study7.o study7.exe
	del study72.o study72.exe
	del study73.o study73.exe
	del study8.o study8.exe
	del iodes.o iodes.exe
	del test.o test.exe
all:
