/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loadtrend_lib_sound_VistaAudioDevice */

#ifndef _Included_com_loadtrend_lib_sound_VistaAudioDevice
#define _Included_com_loadtrend_lib_sound_VistaAudioDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_MAIN_NAME
#define com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_MAIN_NAME 0L
#undef com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_INTERFACE_NAME
#define com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_INTERFACE_NAME 1L
#undef com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_MAIN_INTERFACE_NAME
#define com_loadtrend_lib_sound_VistaAudioDevice_DEVICE_MAIN_INTERFACE_NAME 2L
/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    initializeAudioDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_initializeAudioDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    destroyAudioDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_destroyAudioDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getCaptureDeviceListCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getCaptureDeviceListCount
  (JNIEnv *, jclass);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getCaptureListDeviceName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getCaptureListDeviceName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getCaptureListDeviceId
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getCaptureListDeviceId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getDefaultCaptureDeviceId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getDefaultCaptureDeviceId
  (JNIEnv *, jclass);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getCaptureListDeviceState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getCaptureListDeviceState
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    setCaptureListDeviceVolume
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_setCaptureListDeviceVolume
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    getCaptureListDeviceVolume
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_getCaptureListDeviceVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    setEndpointVisibility
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_setEndpointVisibility
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    setDefaultEndpoint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_setDefaultEndpoint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_loadtrend_lib_sound_VistaAudioDevice
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loadtrend_lib_sound_VistaAudioDevice_testString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
