/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loadtrend_lib_sound_VistaAudioDevice_AudioDevice */

#ifndef _Included_com_loadtrend_lib_sound_VistaAudioDevice_AudioDevice
#define _Included_com_loadtrend_lib_sound_VistaAudioDevice_AudioDevice
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
